window.FIREWORKS={
generated:"2026-09-18",
source:"https://www.worksafe.wa.gov.au/schedule-fireworks-events",
updated:"18 September 2026",
window:"18 September 2026 to 03 October 2026",
guidance:"provided for guidance only",
disclaimers:["Start times and duration may vary from that indicated in the schedule.", "While the department regulates the safe use of fireworks, it does not manage the fireworks displays. For specific information relating to any individual display, please contact the event organiser directly."],
events:[
{"date": "2026-09-19", "day": "Saturday", "time": "7:30 PM", "dur": "2 minutes intermittent", "venue": "RAC Arena", "street": "Wellington St", "suburb": "Perth", "postcode": "6000", "purpose": "Perth Wildcats vs SE Melbourne Phoenix", "close": true, "zone": "central"},
{"date": "2026-09-20", "day": "Sunday", "time": "4:00 PM to 7:30 PM", "dur": "2 x 30 seconds", "venue": "Optus Stadium", "street": "Victoria Park Dr", "suburb": "Burswood", "postcode": "6100", "purpose": "WAFL Grand Finals", "close": true, "zone": "east"},
{"date": "2026-09-24", "day": "Thursday", "time": "7:30 PM", "dur": "2 minutes intermittent", "venue": "RAC Arena", "street": "Wellington St", "suburb": "Perth", "postcode": "6000", "purpose": "Perth Wildcats vs Adelaide 36ers", "close": true, "zone": "central"},
{"date": "2026-09-26", "day": "Saturday", "time": "7:30 PM", "dur": "2 minutes intermittent", "venue": "RAC Arena", "street": "Wellington St", "suburb": "Perth", "postcode": "6000", "purpose": "Perth Wildcats vs BNZ Breakers", "close": true, "zone": "central"},
{"date": "2026-09-26", "day": "Saturday", "time": "8:00 PM", "dur": "15 minutes each night", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Perth Royal Show 2026", "close": false, "zone": "other"},
{"date": "2026-09-27", "day": "Sunday", "time": "8:00 PM", "dur": "15 minutes each night", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Perth Royal Show 2026", "close": false, "zone": "other"},
{"date": "2026-09-28", "day": "Monday", "time": "8:00 PM", "dur": "15 minutes each night", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Perth Royal Show 2026", "close": false, "zone": "other"},
{"date": "2026-09-29", "day": "Tuesday", "time": "8:00 PM", "dur": "15 minutes each night", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Perth Royal Show 2026", "close": false, "zone": "other"},
{"date": "2026-09-30", "day": "Wednesday", "time": "8:00 PM", "dur": "15 minutes each night", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Perth Royal Show 2026", "close": false, "zone": "other"},
{"date": "2026-10-01", "day": "Thursday", "time": "4:30 PM", "dur": "5 minutes", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Veterans Day Demonstration", "close": true, "zone": "other"},
{"date": "2026-10-01", "day": "Thursday", "time": "8:00 PM", "dur": "15 minutes each night", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Perth Royal Show 2026", "close": false, "zone": "other"},
{"date": "2026-10-02", "day": "Friday", "time": "7:30 PM", "dur": "2 minutes intermittent", "venue": "RAC Arena", "street": "Wellington St", "suburb": "Perth", "postcode": "6000", "purpose": "Perth Wildcats vs Melbourne United", "close": true, "zone": "central"},
{"date": "2026-10-02", "day": "Friday", "time": "8:00 PM", "dur": "15 minutes each night", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Perth Royal Show 2026", "close": false, "zone": "other"},
{"date": "2026-10-03", "day": "Saturday", "time": "8:00 PM", "dur": "15 minutes each night", "venue": "Claremont Showgrounds", "street": "Graylands Rd", "suburb": "Claremont", "postcode": "6010", "purpose": "Perth Royal Show 2026", "close": false, "zone": "other"},
]};
