// Transperth (PTA) service disruptions relevant to the City of Perth.
// Shared by east-perth-public-notices.html, central-zone-public-notices.html, west-zone-public-notices.html.
// Source of record: pta-disruptions-db.json. Regenerated on weekly recrawl - do not hand-edit.
// last_scrape: 2026-09-04
window.PTA_DATA = [
  { id: "21697-1", zones: ["east"], mode: "cat", sev: "medium", title: "Red CAT - Nile St & Matagarup Stops Closed", routes: "Red CAT", start: "22/06/2026", end: "", ongoing: true, loc: "Nile St / Matagarup Bridge, East Perth", stops: "Nile Street, Matagarup Bridge CAT stops", impact: "Two East Perth CAT stops closed (ongoing)", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/21697-1", pts: [[-31.955613,115.880105,"Nile Street (CAT 74)"], [-31.956509,115.88379,"Matagarup Bridge (CAT 79)"]] },
  { id: "21126", zones: ["west"], mode: "cat", sev: "low", title: "CATs & Routes 24, 27, 103, 935 - Harvest Tce Stop Closed", routes: "Blue, Green & Purple CATs, Routes 24, 27, 103, 935", start: "16/04/2026", end: "", ongoing: true, loc: "Harvest Terrace, West Perth", stops: "Harvest Terrace CAT stop (ID 29)", impact: "Single West Perth CAT/bus stop closed (ongoing)", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/21126", pts: [[-31.952802,115.84747,"Malcolm St / Harvest Terrace (CAT 29)"]] },
  { id: "20314", zones: ["west"], mode: "bus", sev: "low", title: "Routes 15, 402, 403 & 404 - Newcastle St Stop Closed", routes: "Routes 15, 402, 403 & 404", start: "15/01/2025", end: "", ongoing: true, loc: "Newcastle St, West Perth", stops: "Newcastle St before Golding St (ID 27618)", impact: "Single West Perth bus stop closed (ongoing)", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/20314", pts: [[-31.940848,115.849096,"Newcastle St after Golding St"]] },
  { id: "25238", zones: ["central"], mode: "train", sev: "high", title: "Airport & Fremantle Lines - Nightly Closures", routes: "Airport & Fremantle lines", start: "06/09/2026", end: "10/09/2026", ongoing: false, loc: "Perth Station", stops: "Perth Station (lines closed toward Claremont/Fremantle)", impact: "Lines disrupted nightly from Perth to Claremont and Perth to Fremantle; replacement buses each night", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/25238", pts: [[-31.95118,115.86004,"Perth Station"]] },
  { id: "perth-station-escalator-works-10", zones: ["central"], mode: "train", sev: "low", title: "Perth Station - Escalator Works", routes: "Perth Station (platforms 8/9 escalators)", start: "17/08/2026", end: "04/09/2026", ongoing: false, loc: "Perth Station", stops: "Perth Station, escalators between platforms 8/9 and the overpass", impact: "Escalators between platforms 8/9 and the station overpass out of service daily 6am-4pm for maintenance; stairs and lifts available at the eastern end of platforms 8 & 9", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/perth-station-escalator-works-10", pts: [[-31.95118,115.86004,"Perth Station"]] },
  { id: "routes-40-41-42-and-43-timetable-change", zones: ["central"], mode: "bus", sev: "low", title: "Routes 40, 41, 42 & 43 - Lord St Timed Stop Change", routes: "Routes 40, 41, 42 & 43", start: "23/08/2026", end: "", ongoing: true, loc: "Lord St, Perth (near HBF Park)", stops: "New timed stops: Lord St before Bulwer St (ID 11317), Lord St after Coolgardie Tce (ID 11656)", impact: "From Sun 23 Aug, minor timetable adjustment: Mt Lawley TAFE (Highgate/Mount Lawley, outside the City) no longer a timed stop; HBF Park stops on Lord St, Perth become the new timed checkpoint", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/routes-40-41-42-and-43-timetable-change", pts: [[-31.945859,115.871893,"Lord St before Bulwer St (near HBF Park)"], [-31.946238,115.871786,"Lord St after Coolgardie Tce"]] },
  { id: "25421", zones: ["central", "east"], mode: "train", sev: "medium", title: "Airport, Armadale, Ellenbrook, Midland & Thornlie-Cockburn Lines - WAFL Grand Final Disruption", routes: "Airport, Armadale, Ellenbrook, Midland & Thornlie-Cockburn lines", start: "20/09/2026", end: "20/09/2026", ongoing: false, loc: "McIver & Claisebrook Stations", stops: "McIver Station (closed ~3.51pm-5.51pm); Claisebrook & McIver Platform 3 (closed ~11.17am-12.47pm); Claisebrook Platform 1 (closed ~3.50pm-5.50pm)", impact: "Sun 20 Sep, disrupted for Optus Stadium services ahead of the WAFL Grand Final: McIver Station closed ~3.51-5.51pm (bus from Wellington St); Claisebrook & McIver Platform 3 closed ~11.17am-12.47pm; Claisebrook Platform 1 closed ~3.50-5.50pm; Thornlie-Cockburn Line skips Victoria Park, Burswood, Claisebrook & McIver for much of the day", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/25421", pts: [[-31.95184222233562,115.86650555551078,"McIver Station Platform 1"], [-31.949637777833214,115.87230833330884,"Claisebrook Station Platform 1"]] },
  { id: "25448", zones: ["west"], mode: "cat", sev: "low", title: "Route 24, 950 & Purple CAT - Hampden Rd Stop Closed", routes: "Route 24, Route 950 & Purple CAT", start: "12/09/2026", end: "12/09/2026", ongoing: false, loc: "Hampden Rd, Nedlands", stops: "Hampden Rd Hampden Road South CAT stop (ID 17393 / CAT ID 128)", impact: "Single Nedlands CAT/bus stop closed for road closures, affecting Route 24 (to East Perth), Route 950 (to QEII Medical Centre) and Purple CAT; nearest alternative stops at Karella St (CAT 129) and Cooper St (CAT 127)", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/25448", pts: [[-31.976053,115.813513,"Hampden Rd Hampden Road South (CAT 128)"]] },
  { id: "25480", zones: ["central"], mode: "train", sev: "low", title: "Airport & Fremantle Lines - Platform Change to Perth Underground", routes: "Airport & Fremantle lines", start: "04/10/2026", end: "04/10/2026", ongoing: false, loc: "Perth Underground Station", stops: "Perth Underground Station (Airport & Fremantle lines run from here instead of Perth Station)", impact: "Sun 4 Oct, Airport and Fremantle line trains will run from Perth Underground instead of Perth Station, to facilitate works on the Airport, Ellenbrook and Midland lines", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/25480", pts: [[-31.951569,115.858099,"Perth Underground Station Platform 1"]] },
  { id: "25463", zones: ["central"], mode: "train", sev: "high", title: "Armadale & Thornlie-Cockburn Lines - Day Closure", routes: "Armadale & Thornlie-Cockburn lines", start: "04/10/2026", end: "04/10/2026", ongoing: false, loc: "Perth Station", stops: "Perth Station (Armadale Line disrupted Perth-Perth Stadium; Thornlie-Cockburn Line disrupted Perth-Beckenham)", impact: "Sun 4 Oct, full-day closure: the Armadale Line will be disrupted between Perth and Perth Stadium and the Thornlie-Cockburn Line between Perth and Beckenham", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/25463", pts: [[-31.95118,115.86004,"Perth Station"]] },
  { id: "25479", zones: ["central"], mode: "train", sev: "high", title: "Airport, Ellenbrook & Midland Lines - Day Closure", routes: "Airport, Ellenbrook & Midland lines", start: "04/10/2026", end: "04/10/2026", ongoing: false, loc: "Perth Station", stops: "Perth Station (lines disrupted Perth-High Wycombe, Perth-Ellenbrook, Perth-Midland)", impact: "Sun 4 Oct, full-day closure: the Airport, Ellenbrook and Midland lines will be disrupted from Perth to High Wycombe, Perth to Ellenbrook and Perth to Midland", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/25479", pts: [[-31.95118,115.86004,"Perth Station"]] },
  { id: "25470", zones: ["east"], mode: "bus", sev: "low", title: "Routes 38, 220 & 960 - Plain St Stop Closed", routes: "Routes 38, 220 & 960", start: "08/09/2026", end: "08/09/2026", ongoing: false, loc: "Plain St, East Perth", stops: "Plain St after Hay St (ID 16904)", impact: "Tue 8 Sep, single East Perth bus stop closed for routes 38 (to Cloverdale), 220 (to Armadale Station) and 960 (to Curtin University Bus Station); nearest alternative stops at Adelaide Tce Westend Causeway (10138/10139) and Old Girls School CAT stop (12912)", url: "https://www.transperth.wa.gov.au/Service-Updates/Service-Update-Details/25470", pts: [[-31.959972,115.875014,"Plain St after Hay St (16904)"]] },
];
